import { Clock3, MonitorCheck, WifiOff } from "lucide-react";
import { campuses, dashboardStats } from "@/lib/mock-data";
export default function DashboardPage() {
  return <div className="p-5 lg:p-8"><div className="mb-7"><h1 className="text-3xl font-bold text-[#07172c]">Operations overview</h1><p className="mt-2 text-slate-500">Live estate health and publishing activity across Taletso TVET College.</p></div>
    <section aria-label="Key metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{dashboardStats.map(([label,value,note]) => <article key={label} className="card p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mono mt-3 text-3xl font-bold text-[#07172c]">{value}</p><p className="mt-2 text-xs text-slate-400">{note}</p></article>)}</section>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.7fr_1fr]"><section><h2 className="mb-3 text-lg font-bold text-[#07172c]">Campus estate</h2><div className="grid gap-4 sm:grid-cols-2">{campuses.map((campus) => <article key={campus.code} className="card p-5"><p className="font-bold text-[#07172c]">{campus.name}</p><p className="mono text-xs text-slate-400">{campus.code} · 3 displays</p><div className="mt-5 flex gap-5 text-sm"><span className="flex items-center gap-2 text-emerald-700"><MonitorCheck size={17}/>{campus.online} online</span>{campus.offline > 0 && <span className="flex items-center gap-2 text-rose-600"><WifiOff size={17}/>{campus.offline} offline</span>}</div><div className="mt-5"><div className="mb-1 flex justify-between text-xs"><span>Site readiness</span><span>{campus.readiness}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[#e4ac45]" style={{width:`${campus.readiness}%`}}/></div></div></article>)}</div></section>
    <section><h2 className="mb-3 text-lg font-bold text-[#07172c]">Recent activity</h2><div className="card divide-y divide-slate-100">{["Registration Week submitted for approval","Open Day campaign scheduled","LEH-ADMIN-01 went offline","NSFAS Reminder approved"].map((event,index)=><div key={event} className="flex gap-3 p-4"><Clock3 size={18} className="mt-1 text-[#b07822]"/><div><p className="text-sm font-medium">{event}</p><p className="mt-1 text-xs text-slate-400">{index+1} hours ago</p></div></div>)}</div></section></div>
  </div>;
}
